datacarpentry/python-socialsci

- _episodes/03-control-structures.md
I fixed a few typos in addition to changing sum as a loop variable to cur_sum with a note about why that's important.  
I also removed the warnings about not running the infinite while loop and made the text about how to kill an infinite loop more explicit, as discussed on slack.
> Fixes #20, other improvements to while loop section

- _episodes/02-basics.md
- _episodes/03-control-structures.md
- _episodes/06-json.md
- _episodes/08-extracting-data.md
- _episodes/12-matplotlib.md
- _episodes/13-sqlite.md
Based on Data Carpentry ecology lecture, close #4
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a …
> Add time estimates

- _episodes/01-introduction.md
> Added languages supported by Jupyter; fixed minor typos.

- _episodes/01-introduction.md
> Added Mac keyboard shortcut to run cell

- _episodes/03-control-structures.md
> Change quotes to properly format code

- _episodes/02-basics.md
- _episodes/03-control-structures.md
- _episodes/04-reusable.md
- _episodes/05-processing-data-from-file.md
- _episodes/06-date-and-time.md
No need to merge this yet. I'm sending a pull request because I just updated the output cells for the first chapter where there is code (02-basics). Would you review and let me know if this is fine? It would be a good point to check in, since I'll follow the same pattern for the other chapters.
At some point, we might want to break some of these code cells and output into smaller matching chunks, but no need for now.
If you have any edits to the approach, please modify and show a sample in this pull request and send it back over. Thanks!
> work in progress: add output to code chunks for chapter 02-basics

- _episodes/01-introduction.md
I just read through the intro lecture and tried to clarify some things. This is best viewed by using word diff.
> Update intro lecture language and formatting

- _episodes/06-json.md
#11 
add output for chapter06-json code chunks.  Long output was truncated with '...'
> add output fields for chapter 06-json

- README.md
- _episodes/06-date-and-time.md
making the readme more inclusivev
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, …
> adding who this is for  "and others"

- _episodes/02-basics.md
> Condense, organize ep02 objectives

- _episodes/02-basics.md
- _episodes/03-control-structures.md
- _episodes/04-reusable.md
- _episodes/05-processing-data-from-file.md
- _episodes/06-date-and-time.md
- _episodes/06-json.md
- _episodes/07-Pandas.md
- _episodes/08-extracting-data.md
- _episodes/09-aggregations.md
- _episodes/10-joins.md
- _episodes/11-long-and-wide.md
- _episodes/12-matplotlib.md
- _episodes/13-sqlite.md
By changing the types of code blocks from `.python` to `.language-python`, we will be able to see syntax highlighting once that is available in the lesson.
> Add syntax highlighting to Python code

- _episodes/07-json.md
The output is truncated, so "..." is added to indicate the
output is truncated.
Addresses issue #48
> Add elipsis to Ep 7 example

- _episodes/02-basics.md
"both" doesn't seem to work here. It seems like it should be replaced with "run" or "work".
---
> word missing/wrong word

- _episodes/02-basics.md
> should be would not woulf

- _episodes/03-control-structures.md
A period is needed after code.
> Period needed after sentence

- index.md
To fix pre-req box formatting.
> add callout tag

- _config.yml
lesson was accidentally tagged as lc
> change to dc

- _episodes/02-basics.md
- _episodes/03-control-structures.md
- _episodes/04-reusable.md
- _episodes/05-processing-data-from-file.md
- _episodes/06-date-and-time.md
- _episodes/07-json.md
- _episodes/08-Pandas.md
- _episodes/09-extracting-data.md
- _episodes/10-aggregations.md
- _episodes/11-joins.md
- _episodes/12-long-and-wide.md
- _episodes/13-matplotlib.md
- _episodes/14-sqlite.md
I fixed few typos and a lot of formatting issues, i.e. python syntax as python cell etc., throughout all episodes. All the suggestions from issue #9 should be addressed now.
> corrected typos and formatting errors

- _episodes/01-introduction.md
Hi team! I am interested in getting involved in developing this lesson. In that spirit, I wanted to make a first PR to help improve and standardize the first episode. If you think these changes are productive, I can do the same with the other episodes. This would also help me familiarize myself with the rest of the curriculum as it stands.
**Summary of changes**
- removed slanted quotes
- added `$ jupyter notebook` command line prompt (with bash styling)
- minor wording changes
- italicized menubar instructions (e.g., *Cell > Cell Type*)
- added a link to Markdown Wikipedia page
- reworded the final paragraph to match terminology like In/Out
Changes to comply with [The Carpentries Style Guide](http://carpentries.github.io/lesson-example/06-style-guide/index.html)
- bolded first use of …
> Cleanup in episode 01

- index.md
---
This pull request solves part of issue #38 were the maintainers names were missing. This is also a contribution towards my instructor checkout requirements.
---
> Adding maintainers names

- _episodes/06-date-and-time.md
In
https://datacarpentry.org/python-socialsci/06-date-and-time/index.html
https://github.com/datacarpentry/python-socialsci/edit/gh-pages/_episodes/06-date-and-time.md
While reading the following 3 consecutive phrases, 'a' and 'c' seem more connected when placed one after another and preserves the flow of the discussion. We may choose to move 'b' further down, near the code.
a. You have to tell Python how the various parts of the date and/or time are represented in your 'string'.
b. To use the date and time functions you need to import the `datetime` module.
c. You can do this by creating a `format`.
> Improve the discussion flow in 06-date-and-time.md

- _episodes/01-introduction.md
Changing language of objectives from passive to active.
---
> amending language of objectives

- _episodes/02-basics.md
The line of code her is duplicated, and so it can be deleted or changed to illustrate something. I changed it as well as the output.
> Duplicate line of code

- _episodes/03-control-structures.md
I changed the input text to match the output text in this example.
> Changing input text to match output text

- _episodes/03-control-structures.md
I replaced the word missing with leaving in that sentence.
> Replaced missing with leaving

- _episodes/04-reusable.md
This code is missing a closing parenthesis.
> closing parenthesis is needed here

- _episodes/04-reusable.md
For this code to run it should be "items_str" not "item_str"
> needs to be items_str

- _episodes/04-reusable.md
I added "items_owned" list to line of code so it would run correctly
> Added "items_owned" list to line of code

- _episodes/02-basics.md
The first commit simplifies the reminder example where only the % operator is used.  The motivation comes from % being one of the most difficult operators to understand, and adding order of evaluation on top of it makes it more complex.
Optionally, I added a second commit that adds an example of order of operations that was only previously mentioned in the text with regards to the reminder example.
> Episode 2: simplify reminder example

- _episodes/04-reusable.md
There were typos in the code here I think: an "s" is missing and a closing parenthesis. I also think the output should be 4 and not 9.
> Fixed typos in code and output

- _episodes/04-reusable.md
I think this should be "parentheses" here and not "brackets".
> change "brackets" to "parentheses"

- _episodes/11-joins.md
This PR is mainly a review of #127 with the requested changes. The original PR author may also merge this into their fork, so the original PR is merged instead of this one.
Best,
V
> Episode 11: Adding links and improving data download instructions.

- _episodes/02-basics.md
This is a suggestive fix for #135.
> Episode 2: split output box of string methods demonstration.

- _episodes/13-matplotlib.md
Hi,
this PR attempts to improve Episode 13 (Data visualisation using Matplotlib).
Summary of changes:
- Removes two repeated sections ('Plotting with Pandas' and 'Saving a Graph')
- Edits formatting of library names
- Adds import code to code block in 'Customising our plots with Matplotlib' section
- Edits the file path when importing a dataset and adds a reminder about file paths
Thanks to Jelmer Poelstra from OSU for pointing out these issues in the episode.
Best,
Vini
> Improving Episode 13.

- setup.md
Hi,
This is a follow-up on #163 to further improving setup instructions. Thanks to Jelmer Poelstra from OSU for pointing it out.
Best,
Vini
> setup.md: add instruction of where to place files.

- _episodes/02-basics.md
Hi, I noticed this dead link during our workshop, and replaced it with an existing one.
Summary of changes:
- Remove dead link from string indexing section.
- Replace with new link from Real Python website (should be more stable).
Best,
Vini
> Remove dead link from Episode 02

- _episodes/04-reusable.md
Hi,
this PR improves the 'Volume of a cube' challenge.
Summary of changes:
- Fix code block tag at start of 'Using libraries' section.
- Rename and improve 'Volume of a cube' challenge.
- Improve and extend answer.
- Use lowercase letters for function arguments.
The latter three changes were made following feedback from a workshop learner.
Best,
Vini
> Improving 'Volume of a cube' challenge

- _episodes/11-joins.md
Hi,
here are some minor (tentative) improvements for Episode 11.
Summary of changes:
- Trim line lengths
- Add `pd.concat()` command with `ignore_index=True`
- Rename exercise at the end of the episode
Best,
Vini
> Trim line lengths and add command

- learners/setup.md
Remove a trailing slash that breaks a link.
> rm trailing slash
